### ISSUE TITLE
Worker Main Menu System

### ISSUE THREAD

**Issue by mucnjakf** [mucnjakf/project-oicar-sisanje.hr#36]
Implement worker main menu system

- [ ] Calendar Menu #30 
- [ ] New Appointments Panel #31 
- [ ] Appointment Control #32 
- [ ] Create Appointment Manually  #33 
- [ ] Creating Alternate Appointment #34
- [ ] Select Detailed Appointment #35
