### ISSUE TITLE
Hair Salon Management System

### ISSUE THREAD

**Issue by mucnjakf** [mucnjakf/project-oicar-sisanje.hr#43]
- implement hair salon management system
- [ ] Table List of Hair Salons
- [ ] Custom Control/Panel for Hair Salon
- [ ] Detailed View Hair Salon
- [ ] Add New Hair Salon
- [ ] Edit Hair Salon
- [ ] Disable Hair Salon
- [ ] Navigation Button - Back to Main Menu
