### ISSUE TITLE
Worker Management System

### ISSUE THREAD

**Issue by mucnjakf** [mucnjakf/project-oicar-sisanje.hr#44]
- implement worker management system
- [x] Table List of Workers #51
- [x] Custom Control/Panel for Worker #52
- [x] Detailed View Worker #53 
- [x] Add New Worker #54 
- [x] Edit Worker #55 
- [x] Delete Worker #56 
- [x] Navigation Button - Back to Main Menu
