### ISSUE TITLE
Owner Management System

### ISSUE THREAD

**Issue by mucnjakf** [mucnjakf/project-oicar-sisanje.hr#64]
- implement owner management system
- [x] Table List of Owners #65 
- [x] Custom Control/Panel for Owner  #66 
- [x] Detailed View Owner #67 
- [x] Add New Owner #68 
- [x] Edit Owner #69 
- [x] Delete Owner #70 
- [x] Navigation Button - Back to Main Menu
