### ISSUE TITLE
Registered User Management System

### ISSUE THREAD

**Issue by mucnjakf** [mucnjakf/project-oicar-sisanje.hr#71]
- implement registered user management system
- [x] Table List of Registered Users #72 
- [x] Custom Control/Panel for Registered User #73 
- [x] Detailed View Registered User #74 
- [x] Add New Registered User #75 
- [x] Edit Registered User #76 
- [x] Delete Registered User #77 
- [x] Navigation Button - Back to Main Menu
