### ISSUE TITLE
Worker Main Menu System

### ISSUE THREAD

**Issue by mucnjakf** [mucnjakf/project-oicar-sisanje.hr#81]
- implement worker main menu system
- [ ] Worker Calendar System
- [ ] Table List of New Appointments
- [ ] Custom Control/Panel for New Appointment
- [ ] Detailed View Appointment
- [ ] Add New Appointment Manually
- [ ] Add Alternate Appointment
- [ ] Navigation Button - Logout
